### ISSUE TITLE
How does your Github Pages site work?

### ISSUE THREAD

**Issue by epogrebnyak** [zverok/zverok.github.io#4]
Hi Victor - you have got an exceptionbal clean and readable website here, but unclear how does it happen to work?
Does Githab Pages notice `_config.yml` and then invokes Jekyll and then builds the website out of `index.html~`?

I was expecting more in  `_config.yml` but everything seems commented out )

**Comment by zverok** [comment]
Thanks!
Actually, Jekyll is one of the default engines [recognized by GitHub pages](https://docs.github.com/en/github/working-with-github-pages/setting-up-a-github-pages-site-with-jekyll).
So, most of it is just a default Jekyll theme with the default set of plugins (GitHub pages doesn't allow much of the plugins), with just my small custom CSS fixes here and there :shrug:

**Comment by epogrebnyak** [comment]
So Jekyll takes `index.md` sees default layout in front matter and then renders `index.html` that is served but Github pages from root?

Does `index.html~` have some special role?

As mentioned above - this is a much needed clean theme, Some thing like https://github.com/pages-themes/primer, but witha  menu.

**Comment by zverok** [comment]
> So Jekyll takes index.md sees default layout in front matter and then renders index.html that is served but Github pages from root?

Yes, that's basically what Jekyll does (takes `.md` and renders them according to front matters/configs/etc.)

> Does index.html~ have some special role?

Nope :) It is just default one which I preserved... because I hate to remove stuff :shrug: 

The theme is freshly installed Jekyll's default (or it was when I started the site), I believe it is https://jekyll.github.io/minima/

**Comment by epogrebnyak** [comment]
Thanks for the explainations! Nice to learn minima was a base theme for Jekyll too!
