### ISSUE TITLE
Links to the table of contents don't work on the Grok {Shan, Shui}* blog posts

### ISSUE THREAD

**Issue by pbaam** [zverok/zverok.github.io#7]
Links to the table of contents on each day redirects you to `2021-12-28-grok-shan-shui-inf.html`. The link should redirect you to `2021-12-28-grok-shan-shui.html` instead

```
Part of the _Advent of Grok {Shan, Shui}*_. See [blog post](/blog/2021-12-28-grok-shan-shui-inf.html) for intro and table of contents.
```

**Comment by zverok** [comment]
:facepalm: 
Thanks, fixed!
